services:
  # Redis service for Celery message broker and result backend
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Ollama service for LLM inference
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # Backend FastAPI server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - API_KEYS=dev-key-123,another-key # Replace with your actual keys
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - ollama

  # Celery worker for background tasks
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.worker.celery_app worker --loglevel=info
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - ollama

  # Frontend Nginx server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  ollama_data:
